feat: add missing zone info
FreifunkMD/ffmd_bind9 pull request #10
Opened 2022-12-19 21:39 UTC by 24367dfa

solves #6

2022-12-19 22:34 UTC, penguineer requested changes
Ich habe zwei Änderungswünsche:
* Die Einrückung passt nicht zum Rest (jedenfalls im Diff)
* Es fehlt ein abschließendes Zeilenende

2022-12-19 22:35 UTC, penguineer commented
> solves #6

Only partially unfortunately. I have added a list of hosts that need to be in the zone file.

2022-12-20 10:04 UTC, penguineer commented
Das könnte dann nach #11 kommen, damit wir die Pipeline gleich nutzen können. :)

2022-12-20 12:10 UTC, 24367dfa commented
> Ich habe zwei Änderungswünsche:
> 
> * Die Einrückung passt nicht zum Rest (jedenfalls im Diff)
> * Es fehlt ein abschließendes Zeilenende

Fixed in 8841423cc513d5ec3d90237ca4f45b852fd2db09

2022-12-20 12:11 UTC, 24367dfa commented
> > solves #6
> 
> Only partially unfortunately. I have added a list of hosts that need to be in the zone file.

except for gw1 the missing adressees were added in 55bf8fdae9e25a4a2c66ded2efc9fa7593d0f1bc

2022-12-20 16:14 UTC, 24367dfa commented
rebase istr durch, die requested changes auch. irgendwie bekomme ich das aber nicht als resolved markiert -.-

2022-12-20 16:47 UTC, penguineer commented
> rebase istr durch, die requested changes auch. irgendwie bekomme ich das aber nicht als resolved markiert -.-

Das muss ich machen, indem ich ein neues Review anlegen. Ich würde aber noch auf #11 warten, damit wir das gleich nutzen können.

2022-12-21 13:10 UTC, penguineer commented
@24367dfa Kannst Du diesen Branch bitte noch einmal zum aktuellen HEAD rebasen?

2022-12-21 18:22 UTC, 24367dfa commented
> @24367dfa Kannst Du diesen Branch bitte noch einmal zum aktuellen HEAD rebasen?

/done

2022-12-22 09:08 UTC, penguineer approved these changes

2022-12-22 16:18 UTC, merged